<?php

namespace ContainerLNcfjMj;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getAiVacationControllerService extends App_KernelDevDebugContainer
{
    /**
     * Gets the public 'App\Controller\AiVacationController' shared autowired service.
     *
     * @return \App\Controller\AiVacationController
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/framework-bundle/Controller/AbstractController.php';
        include_once \dirname(__DIR__, 4).'/src/Controller/AiVacationController.php';

        $container->services['App\\Controller\\AiVacationController'] = $instance = new \App\Controller\AiVacationController(($container->privates['http_client.uri_template'] ?? $container->load('getHttpClient_UriTemplateService')), $container->getEnv('OPENAI_API_KEY'));

        $instance->setContainer(($container->privates['.service_locator.8_z8gpu'] ?? $container->load('get_ServiceLocator_8Z8gpuService'))->withContext('App\\Controller\\AiVacationController', $container));

        return $instance;
    }
}
