<?php

namespace ContainerLNcfjMj;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getDebugControllerService extends App_KernelDevDebugContainer
{
    /**
     * Gets the public 'App\Controller\DebugController' shared autowired service.
     *
     * @return \App\Controller\DebugController
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/framework-bundle/Controller/AbstractController.php';
        include_once \dirname(__DIR__, 4).'/src/Controller/DebugController.php';

        $container->services['App\\Controller\\DebugController'] = $instance = new \App\Controller\DebugController();

        $instance->setContainer(($container->privates['.service_locator.8_z8gpu'] ?? $container->load('get_ServiceLocator_8Z8gpuService'))->withContext('App\\Controller\\DebugController', $container));

        return $instance;
    }
}
