<?php

namespace ContainerBDU5qKZ;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getDebugControllersaveScheduleService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.ND3JXoh.App\Controller\DebugController::saveSchedule()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.ND3JXoh.App\\Controller\\DebugController::saveSchedule()'] = (new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'em' => ['privates', '.errored.JQW2.Xj', NULL, 'Cannot determine controller argument for "App\\Controller\\DebugController::saveSchedule()": the $em argument is type-hinted with the non-existent class or interface: "App\\Controller\\EntityManagerInterface". Did you forget to add a use statement?'],
            'repo' => ['privates', 'App\\Repository\\ScheduleRepository', 'getScheduleRepositoryService', true],
        ], [
            'em' => '?',
            'repo' => 'App\\Repository\\ScheduleRepository',
        ]))->withContext('App\\Controller\\DebugController::saveSchedule()', $container);
    }
}
