<?php

namespace ContainerBDU5qKZ;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getDebugControllergetSchedulesService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.CcNLm2Q.App\Controller\DebugController::getSchedules()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.CcNLm2Q.App\\Controller\\DebugController::getSchedules()'] = (new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'repo' => ['privates', 'App\\Repository\\ScheduleRepository', 'getScheduleRepositoryService', true],
        ], [
            'repo' => 'App\\Repository\\ScheduleRepository',
        ]))->withContext('App\\Controller\\DebugController::getSchedules()', $container);
    }
}
