<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerLNcfjMj\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerLNcfjMj/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerLNcfjMj.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerLNcfjMj\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerLNcfjMj\App_KernelDevDebugContainer([
    'container.build_hash' => 'LNcfjMj',
    'container.build_id' => '75db8b31',
    'container.build_time' => 1769109529,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerLNcfjMj');
